name: Deploy to Strato SFTP

on:
  push:
    branches:
      - master

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    name: SFTP Deployment
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload files via SFTP
        uses: afonsomatos/sftp-deploy@v1.2.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.NAME }}
          password: ${{ secrets.PASSWORD }}
          protocol: SFTP
          port: 22
          local-dir: ./ 
          server-dir: ./