name: Deploy to Strato SFTP

on:
  push:
    branches:
      - master

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  deploy:
    name: SFTP Deployment
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload files via SFTP
        uses: appleboy/sftp-action@master
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.NAME }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          local_dir: './'
          remote_dir: './'